// PEAKOPS_CHUNK3B2 — drift guard
// 2026-06-22
//
// Pure-file inspection. Asserts:
//   - createOrgV1 wires the starter-template seed (telecom only)
//   - exportIncidentPacketV1 carries the new branding string in all
//     3 hardcoded spots, with a fallback to "Generated by PeakOps"
//   - All 3 spots accept an optional orgName ctx
//   - The activation playbook + 3 email templates exist
//
// Loud failure if any future refactor walks back the chunk.

import fs from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);

const REPO = "/Users/kesserumini/peakops/my-app";

let failed = 0;
const fail = (msg) => { console.error(`  ❌ ${msg}`); failed++; };
const pass = (msg) => { console.log(`  ✅ ${msg}`); };

console.log("=== createOrgV1 starter-template seed ===");
{
  const path = `${REPO}/functions_clean/createOrgV1.js`;
  const src = fs.readFileSync(path, "utf8");
  if (!/PEAKOPS_STARTER_TEMPLATES_V1/.test(src)) fail("missing PEAKOPS_STARTER_TEMPLATES_V1 marker");
  else pass("PEAKOPS_STARTER_TEMPLATES_V1 marker present");
  if (!/STARTER_TEMPLATES_BY_INDUSTRY/.test(src)) fail("STARTER_TEMPLATES_BY_INDUSTRY const not defined");
  else pass("STARTER_TEMPLATES_BY_INDUSTRY catalog defined");
  if (!/telecom:\s*\{/.test(src)) fail("no telecom entry in starter templates");
  else pass("telecom entry in starter templates");
  if (!/docId:\s*["']fiber_splice_verification["']/.test(src)) fail("telecom starter template not keyed to fiber_splice_verification");
  else pass("telecom starter keyed to fiber_splice_verification");
  if (!/async function seedStarterTemplate\(/.test(src)) fail("seedStarterTemplate helper not defined");
  else pass("seedStarterTemplate helper defined");
  if (!/await seedStarterTemplate\(db,\s*orgId,\s*industry\)/.test(src)) fail("seedStarterTemplate not called from createOrgV1");
  else pass("seedStarterTemplate is called from createOrgV1");
  // Idempotency assertions: existing template never overwritten + best-effort wrapping
  if (!/template_already_exists/.test(src)) fail("seed does not skip when template already exists");
  else pass("seed skips when existing template found (idempotency)");
  if (!/starter_template_seed_failed/.test(src)) fail("seed failure is not best-effort (would block org creation)");
  else pass("seed failure is logged + swallowed (best-effort)");
  // The seed must run AFTER batch.commit() so failure can't tear down the atomic write.
  const commitIdx = src.indexOf("await batch.commit()");
  const seedIdx = src.indexOf("await seedStarterTemplate");
  if (commitIdx === -1 || seedIdx === -1 || seedIdx < commitIdx) {
    fail("seed runs BEFORE batch.commit — failure could tear down org creation");
  } else {
    pass("seed runs AFTER batch.commit (idempotency + best-effort preserved)");
  }
  // Module require check.
  try {
    require(path);
    pass("createOrgV1 module requires cleanly");
  } catch (e) {
    fail(`createOrgV1 require failed: ${e?.message}`);
  }
}

console.log("\n=== exportIncidentPacketV1 packet branding (string-only) ===");
{
  const path = `${REPO}/functions_clean/exportIncidentPacketV1.js`;
  const src = fs.readFileSync(path, "utf8");
  if (!/PEAKOPS_PACKET_BRANDING_V1/.test(src)) fail("missing PEAKOPS_PACKET_BRANDING_V1 marker");
  else pass("PEAKOPS_PACKET_BRANDING_V1 marker present");

  // 1. orgName must be destructured in buildCoverHtml AND buildCustomerHtml.
  const coverDestructMatch = src.match(/function buildCoverHtml\(ctx\)\s*\{[\s\S]*?\}\s*=\s*ctx;/);
  if (!coverDestructMatch || !/orgName/.test(coverDestructMatch[0])) fail("buildCoverHtml does not destructure orgName");
  else pass("buildCoverHtml destructures orgName from ctx");
  const customerDestructMatch = src.match(/function buildCustomerHtml\(ctx\)\s*\{[\s\S]*?\}\s*=\s*ctx;/);
  if (!customerDestructMatch || !/orgName/.test(customerDestructMatch[0])) fail("buildCustomerHtml does not destructure orgName");
  else pass("buildCustomerHtml destructures orgName from ctx");

  // 2. New branded string variant present (powered by PeakOps) — appears in BOTH HTML footers.
  const poweredByCount = (src.match(/powered by PeakOps/g) || []).length;
  if (poweredByCount < 3) fail(`expected ≥3 "powered by PeakOps" sites (2 HTML footers + 1 README); got ${poweredByCount}`);
  else pass(`"powered by PeakOps" appears ${poweredByCount} times across footer + README`);

  // 3. Legacy fallback still present (3 spots: 2 HTML + 1 README).
  // The two HTML spots use ternary; the README uses an if/else. So
  // "Generated by PeakOps · ${...}" should appear ≥2 times (the
  // ternary fallback in both HTML builders), AND the README must
  // carry the standalone fallback message.
  const fallbackHtmlCount = (src.match(/`Generated by PeakOps · \$\{escapeHtml\(formatDateTime/g) || []).length;
  if (fallbackHtmlCount < 2) fail(`expected ≥2 HTML fallback strings; got ${fallbackHtmlCount}`);
  else pass(`HTML fallback string present ${fallbackHtmlCount}x (audit + customer doc)`);
  if (!/readmeLines\.push\("This packet was generated by PeakOps\."\)/.test(src)) {
    fail("README fallback string missing");
  } else {
    pass("README fallback string present");
  }

  // 4. The org lookup itself.
  if (!/let _packetOrgName = null/.test(src)) fail("_packetOrgName not initialized to null (fallback path broken)");
  else pass("_packetOrgName declared with null default");
  if (!/orgs\/\$\{orgId\}/.test(src) || !/_orgDoc\.exists/.test(src)) {
    fail("org-doc lookup pattern not detected");
  } else {
    pass("org-doc lookup uses orgs/{orgId}.exists pattern");
  }
  // The lookup is best-effort — must be inside try/catch.
  const lookupBlock = src.match(/let _packetOrgName = null;[\s\S]*?\} catch \(_e\)/);
  if (!lookupBlock) fail("org lookup is NOT wrapped in try/catch (could block packet generation)");
  else pass("org lookup is best-effort (wrapped in try/catch)");

  // 5. orgName must be passed into BOTH call sites.
  const coverCall = src.match(/coverHtml = buildCoverHtml\(\{[\s\S]*?\}\);/);
  if (!coverCall || !/orgName:\s*_packetOrgName/.test(coverCall[0])) fail("buildCoverHtml call site does not pass orgName: _packetOrgName");
  else pass("buildCoverHtml call site passes orgName: _packetOrgName");
  const customerCall = src.match(/customerHtml = buildCustomerHtml\(\{[\s\S]*?\}\);/);
  if (!customerCall || !/orgName:\s*_packetOrgName/.test(customerCall[0])) fail("buildCustomerHtml call site does not pass orgName: _packetOrgName");
  else pass("buildCustomerHtml call site passes orgName: _packetOrgName");

  // 6. Guardrails — NO logo / NO color / NO PDF / NO cover redesign changes.
  // Make sure the diff didn't sneak in any of these.
  const forbidden = [
    /<img\s+[^>]*logo/i,
    /background-color:[^;]*orgColor/i,
    /generatePdf|pdfkit|puppeteer\b/i,
  ];
  const fwd = ["logo image embedding", "color theming", "PDF generation"];
  for (let i = 0; i < forbidden.length; i++) {
    if (forbidden[i].test(src)) fail(`scope creep: ${fwd[i]} appears in source`);
    else pass(`no ${fwd[i]} in source (scope-locked to string swap)`);
  }
}

console.log("\n=== Documentation ===");
{
  const docs = [
    { path: `${REPO}/docs/CUSTOMER_ACTIVATION_PLAYBOOK.md`, label: "Customer Activation Playbook" },
    { path: `${REPO}/docs/customer-emails/01-welcome.md`, label: "Email 01 — Welcome" },
    { path: `${REPO}/docs/customer-emails/02-day-7-checkin.md`, label: "Email 02 — Day-7 Check-In" },
    { path: `${REPO}/docs/customer-emails/03-day-30-decision.md`, label: "Email 03 — Day-30 Decision" },
  ];
  for (const d of docs) {
    if (!fs.existsSync(d.path)) fail(`${d.label}: file not found at ${d.path}`);
    else {
      const size = fs.statSync(d.path).size;
      if (size < 800) fail(`${d.label}: file is ${size} bytes — too small to be useful`);
      else pass(`${d.label}: present (${size} bytes)`);
    }
  }
  // Playbook references the activate script + cross-links.
  const playbook = fs.readFileSync(`${REPO}/docs/CUSTOMER_ACTIVATION_PLAYBOOK.md`, "utf8");
  if (!/scripts\/activateCustomerOrg\.cjs/.test(playbook)) fail("playbook does not reference activateCustomerOrg.cjs");
  else pass("playbook references activate script");
  if (!/--apply/.test(playbook)) fail("playbook does not mention --apply behavior");
  else pass("playbook documents --apply flag");
  if (!/Day 30/.test(playbook)) fail("playbook missing Day-30 decision gate");
  else pass("playbook covers Day-30 decision gate");
  if (!/founder/i.test(playbook)) fail("playbook does not call out founder escalation paths");
  else pass("playbook documents founder escalation paths");
}

if (failed) {
  console.error(`\n❌ chunk3b2 drift guard: ${failed} failure(s)`);
  process.exit(1);
}
console.log("\n✅ chunk3b2 (starter templates + packet branding + docs) wired correctly");
